server:
  port: 9092
---
spring:

  application:
    name: Inventory-Service

  datasource:
    url: jdbc:mysql://localhost:3306/spring_ecom_inventory
    username: root
    password: RootPass!@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#    properties:
#      hibernate:
#        connection:
#          characterEncoding: utf8mb4
#          characterSetResults: utf8mb4
#          useUnicode: true
#          collation: utf8mb4_unicode_ci
#

